language: php

sudo: false

cache:
  directories:
  - $HOME/.composer/cache/files

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_install:
  - travis_retry composer self-update
  - travis_retry composer update
  - travis_retry composer install