language: php

sudo: false

cache:
  directories:
  - $HOME/.composer/cache/files

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_install:
  - travis_retry composer self-update
  - travis_retry composer update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)