language: php
php:
  - '7.1'
  - '7.2'
before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer require --dev phpunit/phpunit ^7; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then composer require --dev phpunit/phpunit ^8; fi
before_script:
  - composer self-update
  - composer update
  - composer install