# Uncomment the php version that you want to test.
# FROM php:7.1-cli
# FROM php:7.2-cli
# FROM php:7.3-cli
# FROM php:7.4-cli
# FROM php:8.0-cli
# FROM php:8.1-cli
# FROM php:8.2-cli

# Install dependencies
RUN apt update && \
    apt upgrade -y && \
    apt install -y \
    git \
    curl \
    zip \
    unzip

# Install Packages via PECL as not provided by PHP Source
RUN pecl install xdebug \
	&& docker-php-ext-enable xdebug

# Clear cache
RUN apt clean && \
    rm -rf /var/lib/apt/lists/*

# Install composer (get latest v2, change to `--1` if you want to install the latest v1).
RUN curl -sS https://getcomposer.org/installer | php -- --2 --install-dir=/usr/local/bin --filename=composer

COPY . /usr/src/financial-year
WORKDIR /usr/src/financial-year

CMD [ "php"]
