# Workflow name
name: Static Analysis

# Triggers
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
      - 'develop'

# Jobs/Pipelines
jobs:
  phpstan:
    name: 'PHP Stan'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.1, 7.2, 7.3, 7.4, 8.0, 8.1, 8.2 ]
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3
      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
      - name: Update composer to v2
        run: composer self-update --2
      - name: Install Dependencies via Composer
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts --prefer-dist
      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/ tests/
          php_version: "${{ matrix.php }}"
