# Workflow name
name: PHP Unit Tests

# Triggers
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
      - 'develop'

# Jobs/Pipelines
jobs:
  php-unit:
    name: 'PHP Unit'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4
      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
      - name: Update composer to v2
        run: composer self-update --2
      - name: Install Dependencies via Composer
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts --prefer-dist
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
#        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml - Add when coverage is fixed
# ToDo: Add Code Coverage
